mode:
  type: Standalone
  repository:
    type: JDBC
#    props:
#      path: demo

dataSources:
  ds_0:
    dataSourceClassName: com.zaxxer.hikari.HikariDataSource
    driverClassName: com.mysql.cj.jdbc.Driver
    jdbcUrl: jdbc:mysql://192.168.163.128:3306/demo_ds_0?serverTimezone=UTC&useSSL=false&useUnicode=true&characterEncoding=UTF-8&allowPublicKeyRetrieval=true
    username: root
    password: root
    maxPoolSize: 10
  ds_1:
    dataSourceClassName: com.zaxxer.hikari.HikariDataSource
    driverClassName: com.mysql.cj.jdbc.Driver
    jdbcUrl: jdbc:mysql://192.168.163.128:3306/demo_ds_1?serverTimezone=UTC&useSSL=false&useUnicode=true&characterEncoding=UTF-8&allowPublicKeyRetrieval=true
    username: root
    password: root
    maxPoolSize: 10
#  ds_2:
#    dataSourceClassName: com.zaxxer.hikari.HikariDataSource
#    driverClassName: com.mysql.jdbc.Driver
#    jdbcUrl: jdbc:mysql://192.168.163.128:3306/demo_ds_2?serverTimezone=UTC&useSSL=false&useUnicode=true&characterEncoding=UTF-8&allowPublicKeyRetrieval=true
#    username: root
#    password: root
#    maxPoolSize: 10

rules:
- !SHARDING
    autoTables:
      t_order:
        actualDataSources: ds_$->{0..1}
        shardingStrategy:
          standard:
            shardingColumn: order_id
            shardingAlgorithmName: t_order_mod
        keyGenerateStrategy:
          column: order_id
          keyGeneratorName: snowflake_generator
      t_order_item:
        actualDataSources: ds_$->{0..1}
        shardingStrategy:
          standard:
            shardingColumn: order_id
            shardingAlgorithmName: t_order_item_mod
        keyGenerateStrategy:
          column: order_item_id
          keyGeneratorName: snowflake_generator
    bindingTables:
      - t_order,t_order_item
#    defaultDatabaseStrategy:
#      shardingStrategy:
#        standard:
#          shardingColumn: user_id
#          shardingAlgorithmName: database_mod

    shardingAlgorithms:
#      database_mod:
#        type: MOD
#        props:
#          sharding-count: 2
          
      t_order_mod:
        type: MOD
        props:
          sharding-count: 2
      t_order_item_mod:
        type: MOD
        props:
          sharding-count: 2
    keyGenerators:
      snowflake_generator:
        type: SNOWFLAKE
    
- !BROADCAST
    tables:
      - t_address


props:
  sql-show: true
