server:
  port: 9000

spring:
  kafka:
    bootstrap-servers: 127.0.0.1:9092
    producer:
      # bootstrap-servers: 127.0.0.1:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      retries: 0
      batch-size: 16384
      buffer-memory: 33554432
    consumer:
      # bootstrap-servers: 127.0.0.1:9092
      key-serializer: org.apache.kafka.common.serialization.StringDeserializer
      value-serializer: org.apache.kafka.common.serialization.StringDeserializer
      group-id: group-id
      auto-offset-reset: earliest
      enable-auto-commit: true
      auto-commit-interval: 100
